### PR TITLE
Final Pre-Release UI updates

### PR DESCRIPTION
**Pull request by KenEucker**
This PR should include the following updates:

* The Play page, or "home" page, should follow this design, getting rid of the polaroid BikeTag component on this page:
Screen Shot 2022-02-22 at 10 27 23 AM

* The current BikeTagHeader and BikeTagFooter components are to be moved to this page only and formatted as seen in the design above. 

* The new mobile nav and hamburger menu should appear on all other pages, (desktop integration not designed), with the new BikeTagTopMenu and BikeTagBottomMenu components following this design:
Screen Shot 2022-02-22 at 10 28 14 AM
Screen Shot 2022-02-22 at 10 28 19 AM

* The Play sequence should follow the design below and include all of the elements not in the current implementation. All BikeTagButton and BikeTagInput component variants should follow the designs seen below as well.

Screen Shot 2022-02-22 at 10 27 30 AM
Screen Shot 2022-02-22 at 10 27 42 AM
Screen Shot 2022-02-22 at 10 27 53 AM
Screen Shot 2022-02-22 at 10 28 01 AM

* the hint popover modal should look like this:
Screen Shot 2022-02-22 at 4 17 55 PM

* The social icons used across the site for login and social share should come from this design, while those missing should be sourced elsewhere for similar style:

Screen Shot 2022-02-22 at 4 19 16 PM

* The login page is styled after the design below but has two different logins, neither of which are username and password based. One flow is for BikeTag Players and the other flow is for BikeTag Ambassadors. These should look the same and have the same buttonset for initiating the login, but have different looking background and logos. (logo images to come).

Screen Shot 2022-02-22 at 4 21 56 PM

* The Profile page should be built out which is similar to the Player page, only with form fields to change data.

* The login mechanism should work and populate the playerId/ambassadorId and playerName where appropriate, as well as show the profile link opposite of the hamburger menu when logged in.

* The only way to log in will be to visit #/login, no buttons to "log in" will be present for launch.

* The social share should be the meta preview, as shown here:

Screen Shot 2022-02-22 at 7 31 22 PM

### CODE REVIEW

**Comment by KenEucker** [comment]
For the style guide:

**button variants**
light
medium
bold
circle
circle-clean
underline
underline-reverse

**input variants**
regular
read-only
social
password (masked)

** Primary Fonts **
Regular
Bold

**Logos**
original horizontal
secondary stacked with pinwheel
new horizontal with pinwheel

**Colors**
primary
primary-bold
primary-shadow
secondary
secondary-light
secondary-shadow
background
background-shadow

**Comment by KenEucker** [comment]
Changes in this PR should also include the following functionality.

**The user authentication flow:**

1. Player/visitor moves around site -- all requests go through "biketag" source (no authentication needed)
2. Player clicks on play button -- go retrieve authentication by sending user id (raw) or by sending the generic app id ("anonymous" upload)
3. Uses silent oauth 2 flow already available with the backend functions (authorize/token)
4. Depending on the requesting user, BikeTag Ambassador, BikeTag Player, different credentials may be returned for Imgur/Sanity
5. Newly returned authentication is used to create new API using credentials (currently done on every request)

**The BikeTag Ambassador approval flow** 

1. BikeTag Ambassador visits login page, uses netlify login with google account to log in
2. All requests the BikeTag Ambassador uses will be authenticated using the netlify credentials to verify the JWT (just as we do for Auth0)
**3. The `queue` endpoint needs to support more methods. Ideally: GET - getQueue, DELETE - deQueue, PUT - add to queue, POST - submit winning queue tag (what is currently called "approve").**

**The BikeTag Ambassador emails**
1. The queued tag email notification that goes out to BikeTag Ambassadors when a new tag has been submitted/played should be sent after a mystery tag is uploaded (it is currently done on the share-post step)
2. The queued tag email notification should include the current mystery location with a comparison to the uploaded found location images so BikeTag Ambassadors can see if it's correct.
3. The queued tag email notification should include a link with the btaId directing the BikeTag Ambassador to the queue page. The should not need to log in to approve the queue when following the link in this way.
4. The autopost email should match the queued tag email in style.

**Comment by KenEucker** [comment]
Assets for profile icons:

These will be used for when a BikeTag Player or BikeTag Ambassador is logged in and replaces the generic person silhouette image in the designs.

biketag-player
biketag-ambassador

**Comment by KenEucker** [comment]
This Update should also include the new landing page (design coming next week) with the following sections:

Section 1 - What is BikeTag?
Section 2 - How to play?
Section 3 - Leaderboard
Section 4 - The BikeTag Ambassador program
Section 5 - Open Source Project Deployed on Netlify

**Comment by ehoraizon** [comment]
@ehoraizon  contributions:

* Implementation of the play flow component.
* Add interactive google map.
* Add map with region boundary.
* Implementation of Profile page.
* Changes to  UI in the Play page.
* Implementation of name reservation mechanism.
* Changes to UI in About Page.
* General changes to the UI and funcitons.


play_md
play_reserv_name
profile_vue
region_map
about
play_1
play_flow
play_map

**Comment by KenEucker** [comment]
This is all really fantastic work, thank you so much @ehoraizon!!!

Also, many thanks to Rose Weselmann and Jamie Tan and Kelsey Vierow and Natalie Lindquist for aspects of their design and user analysis were incorporated in this work for the release of the new BikeTag App 2.0!! You can see those contributions here:

https://github.com/KenEucker/biketag-vue/issues/53

I will be merging this in and then we are officially soft-launched with a target release to several games on Monday, March 14th! 

This was a huge effort on my part but it would never have been possible without a whole team of people who stepped in to help out with the BikeTag Project. I am very thankful for that.

**Pull request merged**
